/*
  ASSET PIPELINE — run this whenever new photography arrives.

  Everything in public/assets is generated by this script, so the whole site
  stays on one grade. Drop new photographs into tools/source/, point the entries
  below at them, and re-run:

      npm i -D sharp          # not a runtime dependency; only this script needs it
      node tools/build-assets.js

  THE GRADE, and why it is what it is. Three candidates were rendered side by
  side against the original photograph before one was chosen:

    A  darken + a soft-light warm wash      -> stayed hazy, and the lawn's green
                                               dominated the whole frame
    B  desaturate, crush the blacks, THEN
       lay gold over the top                -> chosen
    C  near-greyscale tinted gold           -> turned the photograph sepia; read
                                               as an old picture, not a dark one

  The order in B is the part that matters. Desaturating first stops the grass
  driving the image; crushing the blacks gives the frame somewhere to put the
  white linen; the gold goes on last so it sits in the highlights instead of
  washing everything.

  THE HERO IS A COVER CROP. Scaling to height and cropping to width keeps the
  plate fully photographic top to bottom, so the slow pan behind the headline
  never slides onto empty gradient. It costs an upscale on a small source; the
  grain layer is what makes that read as depth of field rather than as a
  low-resolution original.
*/
import sharp from 'sharp'
import path from 'node:path'
import fs from 'node:fs'
import { fileURLToPath } from 'node:url'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const OUT = path.join(HERE, '..', 'public', 'assets')

/* ---- point these at your photographs ------------------------------------ */

/* The one that fills the hero. Choose the widest, best-lit frame you have:
   it is cropped to a tall 3:4 and panned, so it wants room on all sides. */
const HERO_SOURCE = path.join(HERE, 'source', 'original-01.webp')

/* Square detail crops for the rail down the right of the hero, taken from the
   ORIGINAL pixels so they stay sharp where the upscaled plate cannot.
   left/top/size are in the source image's own coordinates. */
const DETAILS = [
  { name: 'thumb-1', src: HERO_SOURCE, left: 330, top: 395, size: 235 },
  { name: 'thumb-2', src: HERO_SOURCE, left: 575, top: 300, size: 235 },
  { name: 'thumb-3', src: HERO_SOURCE, left: 120, top: 370, size: 235 },
  { name: 'thumb-4', src: HERO_SOURCE, left: 380, top: 560, size: 235 },
]

/* Gallery frames. With more than one photograph, give each its own file and
   drop the crop box — `crop: null` uses the whole frame. */
const GALLERY = [
  { name: 'gallery-1', src: HERO_SOURCE, crop: { left: 0, top: 0, width: 1067, height: 800 } },
  { name: 'gallery-2', src: HERO_SOURCE, crop: { left: 40, top: 330, width: 620, height: 465 } },
  { name: 'gallery-3', src: HERO_SOURCE, crop: { left: 430, top: 250, width: 600, height: 450 } },
  { name: 'gallery-4', src: HERO_SOURCE, crop: { left: 180, top: 520, width: 720, height: 280 } },
]

/* ---- the grade ----------------------------------------------------------- */

const GOLD = '#C9A961'
const svg = (s) => Buffer.from(s)

const grain = (w, h, alpha) => {
  const buf = Buffer.alloc(w * h * 4)
  for (let i = 0; i < w * h; i++) {
    const v = 100 + Math.floor(Math.random() * 56)
    buf[i * 4] = v
    buf[i * 4 + 1] = v
    buf[i * 4 + 2] = v
    buf[i * 4 + 3] = alpha
  }
  return sharp(buf, { raw: { width: w, height: h, channels: 4 } }).png().toBuffer()
}

/* `op` scales the whole wash, so the hero can be pushed hard while the gallery,
   which has to actually show the décor, is barely touched. */
const warmWash = (w, h, op) =>
  svg(`<svg width="${w}" height="${h}" xmlns="http://www.w3.org/2000/svg">
    <defs><linearGradient id="g" x1="0.15" y1="0" x2="0.6" y2="1">
      <stop offset="0%" stop-color="${GOLD}" stop-opacity="${op}"/>
      <stop offset="50%" stop-color="#7A5A2E" stop-opacity="${op * 0.6}"/>
      <stop offset="100%" stop-color="#0A0806" stop-opacity="${op * 1.2}"/>
    </linearGradient></defs>
    <rect width="${w}" height="${h}" fill="url(#g)"/>
  </svg>`)

const vignette = (w, h, strength) =>
  svg(`<svg width="${w}" height="${h}" xmlns="http://www.w3.org/2000/svg">
    <defs><radialGradient id="v" cx="50%" cy="46%" r="78%">
      <stop offset="36%" stop-color="#000" stop-opacity="0"/>
      <stop offset="100%" stop-color="#000" stop-opacity="${strength}"/>
    </radialGradient></defs>
    <rect width="${w}" height="${h}" fill="url(#v)"/>
  </svg>`)

async function hero() {
  const W = 1440
  const H = 1920
  const scaled = await sharp(HERO_SOURCE).resize({ height: H, kernel: sharp.kernel.lanczos3 }).toBuffer()
  const { width: sw } = await sharp(scaled).metadata()

  /* Right of centre: on the original frame this drops most of the staff member
     on the left and centres the run of dressed tables. Set the offset to 0 for
     a straight centre crop on a new photograph. */
  const left = Math.min(sw - W, Math.max(0, Math.round((sw - W) / 2) + 180))

  const base = await sharp(scaled)
    .extract({ left, top: 0, width: W, height: H })
    .modulate({ brightness: 0.82, saturation: 0.4 })
    .linear(1.32, -40)
    .toBuffer()

  await sharp(base)
    .composite([
      { input: warmWash(W, H, 0.5), blend: 'overlay' },
      { input: vignette(W, H, 0.8), blend: 'over' },
      { input: await grain(W, H, 15), blend: 'overlay' },
    ])
    .webp({ quality: 86 })
    .toFile(path.join(OUT, 'hero.webp'))

  console.log(`hero.webp      ${W}x${H}   crop left=${left} of ${sw}`)
}

async function thumbs() {
  for (const d of DETAILS) {
    /* Brighter than the hero: the rail sits ON the dark plate, and at the hero's
       grade it reads as four dark smudges. */
    await sharp(d.src)
      .extract({ left: d.left, top: d.top, width: d.size, height: d.size })
      .resize(200, 200, { kernel: sharp.kernel.lanczos3 })
      .modulate({ brightness: 0.96, saturation: 0.62 })
      .linear(1.16, -14)
      .composite([
        { input: warmWash(200, 200, 0.26), blend: 'overlay' },
        { input: await grain(200, 200, 12), blend: 'overlay' },
      ])
      .webp({ quality: 88 })
      .toFile(path.join(OUT, `${d.name}.webp`))
    console.log(`${d.name}.webp   200x200`)
  }
}

async function gallery() {
  for (const g of GALLERY) {
    const pipe = sharp(g.src)
    if (g.crop) pipe.extract(g.crop)
    const W = 1100
    const meta = g.crop ?? (await sharp(g.src).metadata())
    const H = Math.round((meta.height / meta.width) * W)

    /* A fifth of the hero's wash. These have to sell the décor, so the grade is
       for cohesion only -- it must not hide what is on the table. */
    await pipe
      .resize(W, H, { kernel: sharp.kernel.lanczos3 })
      .modulate({ brightness: 0.94, saturation: 0.72 })
      .linear(1.12, -10)
      .composite([
        { input: warmWash(W, H, 0.2), blend: 'overlay' },
        { input: await grain(W, H, 10), blend: 'overlay' },
      ])
      .webp({ quality: 84 })
      .toFile(path.join(OUT, `${g.name}.webp`))
    console.log(`${g.name}.webp ${W}x${H}`)
  }
}

/* The card a shared link shows. Same grade, so the preview matches the site. */
async function og() {
  const W = 1200
  const H = 630
  const scaled = await sharp(HERO_SOURCE).resize({ width: W, kernel: sharp.kernel.lanczos3 }).toBuffer()
  const { height: sh } = await sharp(scaled).metadata()
  await sharp(scaled)
    .extract({ left: 0, top: Math.max(0, Math.round((sh - H) / 2)), width: W, height: H })
    .modulate({ brightness: 0.82, saturation: 0.4 })
    .linear(1.32, -40)
    .composite([
      { input: warmWash(W, H, 0.5), blend: 'overlay' },
      { input: vignette(W, H, 0.8), blend: 'over' },
    ])
    .webp({ quality: 85 })
    .toFile(path.join(OUT, 'og.webp'))
  console.log(`og.webp        ${W}x${H}`)
}

fs.mkdirSync(OUT, { recursive: true })
await hero()
await thumbs()
await gallery()
await og()
console.log('\ndone ->', OUT)
